### ISSUE TITLE
UI is broken initially 

### ISSUE THREAD

**Issue by Azim-Sabbir** [kinngh/shopify-polaris-playground#1]
here is output -> [preview](https://d.pr/i/2AGY8F)

**Comment by kinngh** [comment]
This is something to do with your setup. The UI isn't broken at all and all of the text doesn't exist in the entire repo. That's either coming from a bad case of copy/paste or something seriously broken in your setup. I'd recommend running a fresh pull and trying again, or figuring out how to replicate in another machine so I can look further into it.


https://github.com/kinngh/shopify-polaris-playground/assets/773555/9bae0056-abd0-47ae-a208-ef56fb88c496
